# Generated by Django 3.2.9 on 2021-11-03 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_auto_20211103_1518'),
        ('books', '0003_book_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='groups',
        ),
        migrations.AddField(
            model_name='book',
            name='groups',
            field=models.ManyToManyField(to='groups.Group'),
        ),
    ]
