# Generated by Django 3.2.9 on 2021-11-03 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_auto_20211103_1821'),
        ('books', '0004_auto_20211103_1716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='groups',
        ),
        migrations.AddField(
            model_name='book',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.group'),
        ),
    ]
