# Generated by Django 3.2.9 on 2021-11-04 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_auto_20211104_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='comments',
            field=models.TextField(null=True),
        ),
    ]
