# Generated by Django 3.2.9 on 2021-11-04 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_book_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='page_count',
            field=models.IntegerField(null=True),
        ),
    ]
