# Generated by Django 3.2.9 on 2021-11-05 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_book_page_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='finished',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True),
        ),
    ]
