# Generated by Django 3.2.9 on 2021-11-09 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_book_avg_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pages_read',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
