# Generated by Django 3.2.9 on 2021-11-09 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_auto_20211103_1821'),
        ('books', '0013_alter_book_pages_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='groups.group'),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.URLField(null=True),
        ),
    ]
