# Generated by Django 3.2.9 on 2021-11-10 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0014_auto_20211109_2008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='options',
        ),
    ]
