# Generated by Django 3.2.9 on 2021-11-13 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0018_auto_20211112_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='finished',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='books.book'),
        ),
    ]
